[config]
autoboot=0
autoboot_list=0
bootwait=4
backlight=50
noticker=1
autohosoff=0
autonogc=1
updater2p=0
bootprotect=1

[Atmosphere]
pkg3=atmosphere/package3
; Only when using EOS
; kip1=atmosphere/kips/loader.kip
kip1patch=nosigchk
emummcforce=1
usb3force=1
icon=bootloader/res/icon_atmosphere.bmp
